// Print Floobyte School(Q.1)

// letprint = "Floobyte School";
// letprint = "A Transferformation in Education";
// console.log("Floobyte School");
// console.log("A Transferformation in Education");

// Multiplyb by 50(Q.2)
// let number= "2";
// console.log("number*50");

// Product of Six(Q.3)
// let one=1;
// let two=2;
// let three=3;
// let four=4;
// let five=5;
// let six=6;
// console.log("one*two*three*four*five*six");

// Sum of five(Q.4)
// let one=1;
// let two=2;
// let three=3;
// let four=4;
// let five=5;
// console.log("one+two+three+four+five");

// Cube of a number(Q.5)
// let n=2;
// console.log("n**3");

// Square and Sum(Q.6)
// let first=2;
// let second=3;
// let third=4;
// console.log("a*a+b*b+c*c");

// Find x(Q.7)
// let x=2;
// console.log("x*5+10");

// Sum of Natural Numbers(Q.8)
// let a=5;
// console.log("(a*(a+1))/2");

// Double all(Q.9)
// let a=1;
// let b=2;
// let c=3;
// let d=4;
// let e=5;
// console.log("(a+b+c+d+e)*2");

//  Infinity Stones(Q.10)
// let a=1;
// let b=2;
// let c=3;
// let d=4;
// let e=5;
// let f=6;
// console.log("a+b*2 + c*3 + d*3 + e*2 + f*2");
